name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          brew update
          brew install cmake 
      
      - name: Run CMake and Run Server and Test
        run: |
          mkdir build
          cd build/
          cmake ..
          make
          cd unittest/
          ./unittest 
      
      - name: Docker meta 
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
           images: jjangchan/axe-test-web-server
           tag-semver: ${{github.sha}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}