name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
           echo ${{ github.workspace }}
           docker run -i --name test-ubuntu ubuntu:20.04 /bin/bash
           exit
           docker start test-ubuntu 
           docker cp ${{ github.workspace }}/. test-ubuntu:/data/
           docker exec -i test-ubuntu /bin/bash
           cd data
           mkdir build
           cd build
           cmake ..
           exit
           docker stop test-ubuntu 
          

 