name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          brew update
          brew install cmake 
      
      - name: Run CMake and Run Server and Test
        run: |
          mkdir build
          cd build/
          cmake ..
          make
          cd unittest/
          ./unittest 