name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          brew update
          brew install cmake boost openssl ninja curl
          brew install cpprestsdk
      
      - name: Run CMake and Run Server and Test
        run: |
          mkdir build
          cd build/
          cmake ..
          make
          ./qraft_exchange_api
          curl -X GET localhost:8090/api/range/0/1000000
          curl -X GET localhost:8090/api/list
          curl -X GET localhost:8090/api/check
          curl -X GET localhost:8090/api/total/aaaa
