name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout sources
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Install dependencies
      #  run: | 
      #    brew update
      #    brew install cmake boost openssl ninja
      #    brew install cpprestsdk

