name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          brew update
          brew install cmake boost openssl ninja curl
          brew install cpprestsdk
      - name: Search directory
        run: |
          cd /usr/local/opt/cpprestsdk/include/
          ls
          cd /usr/local/opt/cpprestsdk/lib/
          ls
          cd /usr/local/opt/openssl/lib/
          ls
          cd /usr/local/opt/openssl/include/
          ls

