name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
           echo ${{github.sha}}
      #    echo ${{ secrets.DOCKER_HUB_USERNAME }} 
      #    brew install cmake 
      
      #- name: Run CMake and Run Server and Test
      #  run: |
      #    echo TEST
      #    mkdir build
      #    cd build/
      #    cmake ..
      #    make
      #    cd unittest/
      #    ./unittest 
      
      - name: Docker meta 
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
           images: jjangchan/axe-test-web-server
           tags: | 
              type=raw,value=${{github.sha}},enable=true


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
